import { Book, PublishingHistoryEntry } from '../types';

export const BOOKS_DATASET: Book[] = [
  // --- RELEASING AUGUST 26, 2026 (TODAY) ---
  {
    id: 'book-001',
    title: 'The Tides of Silver and Stone',
    author: 'Rebecca Yarros',
    authorBio: 'Bestselling fantasy author of The Empyrean series and romantic sagas.',
    publisher: 'Entangled Publishing',
    imprint: 'Red Tower Books',
    coverImage: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Fantasy', 'Romance', 'Adventure'],
    series: {
      name: 'The Empyrean',
      number: 4,
      totalInSeries: 5,
    },
    description: 'In the aftermath of the harrowing Navarre siege, dragon riders and infantry cadets must forge forbidden alliances beyond the mountain borders as ancient glyph magic awakens deep beneath the continental shelf.',
    isbn: '9781649374080',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-26', price: '$32.99', pageCount: 640 },
      { type: 'ebook', releaseDate: '2026-08-26', price: '$15.99' },
      { type: 'audiobook', releaseDate: '2026-08-26', price: '$28.50', narrator: 'Teddy Hamilton & Rebecca Soler', duration: '21 hrs 40 mins' },
      { type: 'paperback', releaseDate: '2027-04-14', price: '$19.99', pageCount: 656 },
    ],
    anticipatedCount: 2430,
    featuredQuote: '“To fly with dragons is to choose death on your own sovereign terms.”',
    pageCount: 640,
    primaryReleaseDate: '2026-08-26',
  },
  {
    id: 'book-002',
    title: 'The Bullet That Missed Nothing',
    author: 'Richard Osman',
    authorBio: 'British television presenter, producer, novelist, and author of The Thursday Murder Club series.',
    publisher: 'Penguin Random House',
    imprint: 'Viking',
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Mystery & Thriller', 'Cozy Mystery', 'Crime'],
    series: {
      name: 'The Thursday Murder Club',
      number: 5,
    },
    description: 'Elizabeth, Joyce, Ron, and Ibrahim return to Coopers Chase for tea and another baffling cold case involving a vanished art forger and a vintage Aston Martin found submerged in an abandoned quarry.',
    isbn: '9780593299418',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-26', price: '$29.00', pageCount: 416 },
      { type: 'ebook', releaseDate: '2026-08-26', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-08-26', price: '$26.00', narrator: 'Fiona Shaw', duration: '11 hrs 15 mins' },
      { type: 'paperback', releaseDate: '2027-02-16', price: '$18.00', pageCount: 432 },
    ],
    anticipatedCount: 1840,
    featuredQuote: '“In life you have to take the rough with the smooth, but at our age, you try to ensure someone else takes the rough.”',
    pageCount: 416,
    primaryReleaseDate: '2026-08-26',
  },
  {
    id: 'book-003',
    title: 'The Echo Protocol',
    author: 'Martha Wells',
    authorBio: 'Award-winning author of The Murderbot Diaries and The Books of the Raksura.',
    publisher: 'Tor Publishing Group',
    imprint: 'Tordotcom',
    coverImage: 'https://images.unsplash.com/photo-1532012164546-f432f2e37264?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Sci-Fi', 'AI & Cyberpunk', 'Space Opera'],
    series: {
      name: 'The Murderbot Diaries',
      number: 8,
    },
    description: 'When an uncharted mining station broadcasts an obsolete distress beacon in encrypted machine code, our favorite SecUnit is forced to postpone a much-anticipated media binge to rescue a crew of hopelessly naive bio-scientists.',
    isbn: '9781250826978',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-26', price: '$24.99', pageCount: 224 },
      { type: 'ebook', releaseDate: '2026-08-26', price: '$12.99' },
      { type: 'audiobook', releaseDate: '2026-08-26', price: '$19.99', narrator: 'Kevin R. Free', duration: '5 hrs 45 mins' },
      { type: 'paperback', releaseDate: '2027-03-02', price: '$16.99' },
    ],
    anticipatedCount: 1950,
    featuredQuote: '“I could become a mass murderer after I hack my governor module, but then I wouldn’t get to finish Season 7 of Sanctuary Moon.”',
    pageCount: 224,
    primaryReleaseDate: '2026-08-26',
  },
  {
    id: 'book-004',
    title: 'A Garden in the Shadowlands',
    author: 'Emily Henry',
    authorBio: '#1 New York Times bestselling author of Book Lovers, Beach Read, and Funny Story.',
    publisher: 'Penguin Random House',
    imprint: 'Berkley',
    coverImage: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Romance', 'Contemporary Fiction', 'Humor'],
    description: 'A fiercely independent architectural landscape designer and her long-time nemesis—a rival historic preservationist—are forced to co-renovate an eccentric gothic estate on the misty shores of Lake Michigan.',
    isbn: '9780593441299',
    formats: [
      { type: 'paperback', releaseDate: '2026-08-26', price: '$19.00', pageCount: 384 },
      { type: 'hardcover', releaseDate: '2026-08-26', price: '$30.00', pageCount: 384 },
      { type: 'ebook', releaseDate: '2026-08-26', price: '$13.99' },
      { type: 'audiobook', releaseDate: '2026-08-26', price: '$24.99', narrator: 'Julia Whelan', duration: '10 hrs 30 mins' },
    ],
    anticipatedCount: 2120,
    featuredQuote: '“Some people leave footprints on your heart; he left blueprints for a house neither of us knew how to build.”',
    pageCount: 384,
    primaryReleaseDate: '2026-08-26',
  },
  {
    id: 'book-005',
    title: 'The Neural Commons',
    author: 'Ed Yong',
    authorBio: 'Pulitzer Prize-winning science journalist and author of An Immense World and I Contain Multitudes.',
    publisher: 'Random House',
    imprint: 'One World',
    coverImage: 'https://images.unsplash.com/photo-1507842229451-9f22be21c127?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Non-Fiction', 'Science & Nature', 'Biology'],
    description: 'An illuminating investigation into how subterranean fungal networks, forest canopies, and cross-species signals form an unbroken planetary sensory tapestry that is rewriting evolutionary biology.',
    isbn: '9780593133255',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-26', price: '$32.00', pageCount: 448 },
      { type: 'ebook', releaseDate: '2026-08-26', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-08-26', price: '$27.50', narrator: 'Ed Yong', duration: '13 hrs 10 mins' },
    ],
    anticipatedCount: 980,
    featuredQuote: '“To comprehend the wilderness, we must first abandon the conceit that human eyes are the primary spectators of the Earth.”',
    pageCount: 448,
    primaryReleaseDate: '2026-08-26',
  },

  // --- AUGUST 2026 (WEEK 1: AUG 1 - AUG 7) ---
  {
    id: 'book-006',
    title: 'The Clockwork Archipelago',
    author: 'Adrian Tchaikovsky',
    authorBio: 'Arthur C. Clarke Award-winning author of Children of Time.',
    publisher: 'Tor Publishing Group',
    imprint: 'Tor Books',
    coverImage: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Sci-Fi', 'Steampunk', 'Fantasy'],
    description: 'On an ocean world where island chains are geared together like immense celestial chronometers, deep-sea salvagers discover a dormant cog that threatens to halt the tides forever.',
    isbn: '9781250865519',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-04', price: '$28.99', pageCount: 512 },
      { type: 'ebook', releaseDate: '2026-08-04', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-08-04', price: '$26.99' },
    ],
    anticipatedCount: 1120,
    primaryReleaseDate: '2026-08-04',
  },
  {
    id: 'book-007',
    title: 'The Silent Sisterhood of Blackwood',
    author: 'Silvia Moreno-Garcia',
    authorBio: 'New York Times bestselling author of Mexican Gothic and The Daughter of Doctor Moreau.',
    publisher: 'Penguin Random House',
    imprint: 'Del Rey',
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Horror', 'Historical Fiction', 'Gothic'],
    description: 'Set in 1920s Veracruz, an asylum physician discovers that the cloistered order of nuns tending to the catatonic ward are practicing an ancient mesoamerican ritual of dream-weaving.',
    isbn: '9780593356821',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-04', price: '$28.00', pageCount: 352 },
      { type: 'ebook', releaseDate: '2026-08-04', price: '$13.99' },
      { type: 'audiobook', releaseDate: '2026-08-04', price: '$22.00' },
    ],
    anticipatedCount: 1670,
    primaryReleaseDate: '2026-08-04',
  },
  {
    id: 'book-008',
    title: 'Where the River Bends Back',
    author: 'Tommy Orange',
    authorBio: 'Pulitzer Prize finalist and author of There There and Wandering Stars.',
    publisher: 'Knopf Doubleday',
    imprint: 'Alfred A. Knopf',
    coverImage: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Literary Fiction', 'Contemporary Fiction', 'Indigenous'],
    description: 'An interwoven family saga following three generations of an urban Native American community in Oakland through personal triumphs, recovery, hip-hop culture, and ancestral remembrance.',
    isbn: '9780525656180',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-05', price: '$29.00', pageCount: 336 },
      { type: 'ebook', releaseDate: '2026-08-05', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-08-05', price: '$25.00' },
    ],
    anticipatedCount: 1340,
    primaryReleaseDate: '2026-08-05',
  },
  {
    id: 'book-009',
    title: 'Interstellar Cartography for Beginners',
    author: 'Travis Baldree',
    authorBio: 'Audiobook narrator and bestselling author of Legends & Lattes and Bookshops & Bonedust.',
    publisher: 'Tor Publishing Group',
    imprint: 'Tor Books',
    coverImage: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Fantasy', 'Cozy Fantasy', 'Sci-Fi'],
    description: 'A retired starship navigator opens a cozy celestial tea bar and chart-making workshop on a sleepy orbital ring, catering to weary smugglers, poet-pilots, and wayward droids.',
    isbn: '9781250886118',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-06', price: '$25.99', pageCount: 288 },
      { type: 'ebook', releaseDate: '2026-08-06', price: '$12.99' },
      { type: 'audiobook', releaseDate: '2026-08-06', price: '$20.00', narrator: 'Travis Baldree' },
    ],
    anticipatedCount: 1890,
    primaryReleaseDate: '2026-08-06',
  },

  // --- AUGUST 2026 (WEEK 2: AUG 8 - AUG 14) ---
  {
    id: 'book-010',
    title: 'Wind and Truth: Part Two',
    author: 'Brandon Sanderson',
    authorBio: '#1 New York Times bestselling author of the Cosmere universe and Mistborn.',
    publisher: 'Tor Publishing Group',
    imprint: 'Tor Books',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Fantasy', 'Epic Fantasy', 'Cosmere'],
    series: {
      name: 'The Stormlight Archive',
      number: 5,
      totalInSeries: 10,
    },
    description: 'The contest of champions reaches its earth-shattering conclusion across Roshar as Kaladin Stormblessed, Shallan Davar, and Dalinar Kholin confront the true nature of the Unmade.',
    isbn: '9781250311207',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-11', price: '$39.99', pageCount: 1240 },
      { type: 'ebook', releaseDate: '2026-08-11', price: '$17.99' },
      { type: 'audiobook', releaseDate: '2026-08-11', price: '$34.99', narrator: 'Michael Kramer & Kate Reading', duration: '55 hrs 30 mins' },
    ],
    anticipatedCount: 4500,
    featuredQuote: '“The most important step a person can take isn’t the first one. It is the next one. Always the next step.”',
    pageCount: 1240,
    primaryReleaseDate: '2026-08-11',
  },
  {
    id: 'book-011',
    title: 'The Guest Room Protocol',
    author: 'Lucy Foley',
    authorBio: 'Bestselling author of The Guest List, The Paris Apartment, and The Midnight Feast.',
    publisher: 'HarperCollins',
    imprint: 'William Morrow',
    coverImage: 'https://images.unsplash.com/photo-1473186578172-c141e6798cf4?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Mystery & Thriller', 'Psychological Thriller', 'Suspense'],
    description: 'A group of wealthy university friends rent an ultra-secluded brutalist lodge in the Scottish Highlands for an anniversary weekend, unaware the property owner has wired every fixture for psychological observation.',
    isbn: '9780063234986',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-11', price: '$29.99', pageCount: 384 },
      { type: 'ebook', releaseDate: '2026-08-11', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-08-11', price: '$25.00' },
    ],
    anticipatedCount: 1420,
    primaryReleaseDate: '2026-08-11',
  },
  {
    id: 'book-012',
    title: 'Algorithm of Desire',
    author: 'Ali Hazelwood',
    authorBio: 'New York Times bestselling author of The Love Hypothesis and Love, Theoretically.',
    publisher: 'Penguin Random House',
    imprint: 'Berkley',
    coverImage: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Romance', 'Romantic Comedy', 'Contemporary Fiction'],
    description: 'A theoretical computer scientist and her sworn academic rival must pretend to be a happily engaged couple to secure a ten-million-dollar robotics grant from an eccentric philanthropic institute.',
    isbn: '9780593638897',
    formats: [
      { type: 'paperback', releaseDate: '2026-08-12', price: '$19.00', pageCount: 400 },
      { type: 'ebook', releaseDate: '2026-08-12', price: '$13.99' },
      { type: 'audiobook', releaseDate: '2026-08-12', price: '$23.50' },
    ],
    anticipatedCount: 1980,
    primaryReleaseDate: '2026-08-12',
  },
  {
    id: 'book-013',
    title: 'The Great Convergence: Rewriting Global Trade',
    author: 'Patrick Radden Keefe',
    authorBio: 'Award-winning staff writer at The New Yorker and author of Empire of Pain and Rogues.',
    publisher: 'Knopf Doubleday',
    imprint: 'Doubleday',
    coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Non-Fiction', 'Investigative Journalism', 'Economics'],
    description: 'A gripping geopolitical and investigative expose on the shadowy shipping cartels and sovereign wealth funds controlling maritime choke points from the Malacca Strait to the Suez.',
    isbn: '9780385549882',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-13', price: '$35.00', pageCount: 496 },
      { type: 'ebook', releaseDate: '2026-08-13', price: '$16.99' },
      { type: 'audiobook', releaseDate: '2026-08-13', price: '$29.00' },
    ],
    anticipatedCount: 1150,
    primaryReleaseDate: '2026-08-13',
  },

  // --- AUGUST 2026 (WEEK 3: AUG 15 - AUG 21) ---
  {
    id: 'book-014',
    title: 'The Cartographer of Lost Tongues',
    author: 'R.F. Kuang',
    authorBio: 'Award-winning author of Babel, Yellowface, and The Poppy War trilogy.',
    publisher: 'HarperCollins',
    imprint: 'Harper Voyager',
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Fantasy', 'Historical Fantasy', 'Literary Fiction'],
    description: 'In 1890s Canton, a linguistic prodigy uncovers an imperial project that systematically erases dialects through enchanted translation ink, igniting a war of grammatical resistance.',
    isbn: '9780063023475',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-18', price: '$30.00', pageCount: 560 },
      { type: 'ebook', releaseDate: '2026-08-18', price: '$15.99' },
      { type: 'audiobook', releaseDate: '2026-08-18', price: '$28.00' },
    ],
    anticipatedCount: 3100,
    featuredQuote: '“To name a world in another tongue is to conquer it without drawing a sword.”',
    pageCount: 560,
    primaryReleaseDate: '2026-08-18',
  },
  {
    id: 'book-015',
    title: 'The Maidens of Devil’s Rock',
    author: 'Riley Sager',
    authorBio: 'New York Times bestselling author of Final Girls, The Only One Left, and Middle of the Night.',
    publisher: 'Penguin Random House',
    imprint: 'Dutton',
    coverImage: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Mystery & Thriller', 'Horror', 'Psychological Thriller'],
    description: 'Forty years after three teenagers vanished from a cliffside boarding school, an archival true-crime documentary filmmaker receives a tape recorded inside the school cellar yesterday.',
    isbn: '9780593472439',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-18', price: '$28.00', pageCount: 384 },
      { type: 'ebook', releaseDate: '2026-08-18', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-08-18', price: '$24.00' },
    ],
    anticipatedCount: 1560,
    primaryReleaseDate: '2026-08-18',
  },
  {
    id: 'book-016',
    title: 'A Little More Light Than Shadow',
    author: 'Hanif Abdurraqib',
    authorBio: 'MacArthur Genius Fellow, poet, cultural critic, and essayist.',
    publisher: 'Hachette Book Group',
    imprint: 'Basic Books',
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Non-Fiction', 'Memoir', 'Essays & Culture'],
    description: 'A poetic and sweeping meditation on live performances, midwestern basketball courts, grief, sonic memory, and the tender ways community gathers in fleeting moments.',
    isbn: '9781541703901',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-19', price: '$29.00', pageCount: 320 },
      { type: 'ebook', releaseDate: '2026-08-19', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-08-19', price: '$24.00', narrator: 'Hanif Abdurraqib' },
    ],
    anticipatedCount: 920,
    primaryReleaseDate: '2026-08-19',
  },
  {
    id: 'book-017',
    title: 'The Iron Crown of Prague',
    author: 'Samantha Shannon',
    authorBio: 'New York Times and Sunday Times bestselling author of The Priory of the Orange Tree.',
    publisher: 'Bloomsbury Publishing',
    imprint: 'Bloomsbury Circus',
    coverImage: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Fantasy', 'Epic Fantasy', 'Historical Fantasy'],
    series: {
      name: 'Roots of Chaos',
      number: 3,
    },
    description: 'In an alternate sixteenth-century Europe guarded by draconic dynasties and alchemical courts, a disgraced diplomat must negotiate a peace treaty with the High Queen of the Eastern Skies.',
    isbn: '9781635579987',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-20', price: '$35.00', pageCount: 768 },
      { type: 'ebook', releaseDate: '2026-08-20', price: '$16.99' },
      { type: 'audiobook', releaseDate: '2026-08-20', price: '$30.00' },
    ],
    anticipatedCount: 2200,
    primaryReleaseDate: '2026-08-20',
  },

  // --- AUGUST 2026 (WEEK 4: AUG 22 - AUG 28) ---
  {
    id: 'book-018',
    title: 'The Last Symphony of Milan',
    author: 'Amor Towles',
    authorBio: 'Bestselling author of A Gentleman in Moscow, The Lincoln Highway, and Rules of Civility.',
    publisher: 'Penguin Random House',
    imprint: 'Viking',
    coverImage: 'https://images.unsplash.com/photo-1507842229451-9f22be21c127?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Historical Fiction', 'Literary Fiction', 'Music'],
    description: 'In 1938 Milan, an aging opera conductor and a young violin prodigy risk everything inside La Scala to conceal an anti-fascist code within the score of a world premiere.',
    isbn: '9780525559498',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-25', price: '$30.00', pageCount: 464 },
      { type: 'ebook', releaseDate: '2026-08-25', price: '$15.99' },
      { type: 'audiobook', releaseDate: '2026-08-25', price: '$27.50' },
    ],
    anticipatedCount: 1780,
    featuredQuote: '“Music does not ask what flag you salute; it asks only how deeply you are willing to bleed for harmony.”',
    pageCount: 464,
    primaryReleaseDate: '2026-08-25',
  },
  {
    id: 'book-019',
    title: 'The Architect of Unfinished Rooms',
    author: 'Maggie O’Farrell',
    authorBio: 'Women’s Prize for Fiction winner and author of Hamnet and The Marriage Portrait.',
    publisher: 'Knopf Doubleday',
    imprint: 'Alfred A. Knopf',
    coverImage: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Historical Fiction', 'Literary Fiction', 'Art'],
    description: 'A sumptuous, spellbinding portrait of Artemisia Gentileschi’s final years in Naples as she secretly constructs a private sanctuary chapel for forgotten women artists.',
    isbn: '9780593535974',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-26', price: '$29.00', pageCount: 384 },
      { type: 'ebook', releaseDate: '2026-08-26', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-08-26', price: '$26.00' },
    ],
    anticipatedCount: 1650,
    primaryReleaseDate: '2026-08-26',
  },
  {
    id: 'book-020',
    title: 'Deep Recursion',
    author: 'James S.A. Corey',
    authorBio: 'Pen name of Daniel Abraham and Ty Franck, authors of The Expanse and The Mercy of Gods.',
    publisher: 'Hachette Book Group',
    imprint: 'Orbit',
    coverImage: 'https://images.unsplash.com/photo-1532012164546-f432f2e37264?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Sci-Fi', 'Space Opera', 'Hard Sci-Fi'],
    series: {
      name: 'The Captive’s War',
      number: 2,
    },
    description: 'Humanity’s captive research team on the Carryx homeworld navigates treacherous biological trials, weaponizing alien bureaucratic rivalries to stage a silent rebellion.',
    isbn: '9780316525602',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-27', price: '$30.00', pageCount: 480 },
      { type: 'ebook', releaseDate: '2026-08-27', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-08-27', price: '$28.00', narrator: 'Jefferson Mays' },
    ],
    anticipatedCount: 2890,
    primaryReleaseDate: '2026-08-27',
  },
  {
    id: 'book-021',
    title: 'A Murder at Midnight Court',
    author: 'Freida McFadden',
    authorBio: '#1 New York Times bestselling author of The Housemaid and The Teacher.',
    publisher: 'Sourcebooks',
    imprint: 'Poisoned Pen Press',
    coverImage: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Mystery & Thriller', 'Psychological Thriller', 'Twisty Mystery'],
    description: 'A defense attorney is assigned to represent a client accused of killing the presiding judge, only to realize the suspect knows every dark secret from the lawyer’s past.',
    isbn: '9781728289410',
    formats: [
      { type: 'paperback', releaseDate: '2026-08-27', price: '$17.99', pageCount: 352 },
      { type: 'ebook', releaseDate: '2026-08-27', price: '$9.99' },
      { type: 'audiobook', releaseDate: '2026-08-27', price: '$18.99' },
    ],
    anticipatedCount: 2310,
    primaryReleaseDate: '2026-08-27',
  },

  // --- AUGUST 2026 (WEEK 5: AUG 29 - AUG 31) ---
  {
    id: 'book-022',
    title: 'The Glass Horizon',
    author: 'Sally Rooney',
    authorBio: 'Acclaimed author of Normal People, Conversations with Friends, and Intermezzo.',
    publisher: 'Farrar, Straus and Giroux',
    imprint: 'FSG',
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Literary Fiction', 'Contemporary Fiction', 'Drama'],
    description: 'A tender, acutely observed study of two former debate partners who reconnect in Dublin during their mid-thirties, navigating ideology, unexpressed love, and modern alienation.',
    isbn: '9780374602642',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-30', price: '$29.00', pageCount: 320 },
      { type: 'ebook', releaseDate: '2026-08-30', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-08-30', price: '$25.00' },
      { type: 'paperback', releaseDate: '2027-05-18', price: '$18.00' },
    ],
    anticipatedCount: 2750,
    primaryReleaseDate: '2026-08-30',
  },
  {
    id: 'book-023',
    title: 'The Botanist of Dead Stars',
    author: 'T.J. Klune',
    authorBio: 'Beloved author of The House in the Cerulean Sea and Under the Whispering Door.',
    publisher: 'Tor Publishing Group',
    imprint: 'Tor Books',
    coverImage: 'https://images.unsplash.com/photo-1473186578172-c141e6798cf4?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Fantasy', 'Cozy Fantasy', 'LGBTQ+'],
    description: 'A whimsical and heartfelt story about an immortal cosmic gardener who rescues fading nebulae and an earnest celestial inspector who arrives to audit his paperwork.',
    isbn: '9781250875329',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-31', price: '$28.99', pageCount: 400 },
      { type: 'ebook', releaseDate: '2026-08-31', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-08-31', price: '$26.00', narrator: 'Daniel Henning' },
    ],
    anticipatedCount: 2190,
    primaryReleaseDate: '2026-08-31',
  },

  // --- SEPTEMBER 2026 RELEASES ---
  {
    id: 'book-024',
    title: 'A Reckoning of Kings',
    author: 'Leigh Bardugo',
    authorBio: '#1 New York Times bestselling author of the Grishaverse and The Familiar.',
    publisher: 'Macmillan',
    imprint: 'Flatiron Books',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Fantasy', 'Dark Fantasy', 'Young Adult'],
    description: 'A razor-sharp heist through the sun-bleached spires of an aristocratic desert empire, where bloodline alchemists and guild thieves plot to steal the emperor’s crown.',
    isbn: '9781250785121',
    formats: [
      { type: 'hardcover', releaseDate: '2026-09-08', price: '$30.00', pageCount: 464 },
      { type: 'ebook', releaseDate: '2026-09-08', price: '$15.99' },
      { type: 'audiobook', releaseDate: '2026-09-08', price: '$27.50' },
    ],
    anticipatedCount: 3400,
    primaryReleaseDate: '2026-09-08',
  },
  {
    id: 'book-025',
    title: 'The Coldest Winter in Dublin',
    author: 'Tana French',
    authorBio: 'Edgar Award-winning author of the Dublin Murder Squad series and The Searcher.',
    publisher: 'Penguin Random House',
    imprint: 'Viking',
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Mystery & Thriller', 'Literary Thriller', 'Crime'],
    description: 'Cal Hooper and Trey Reddy become entangled in a decades-old missing person case when an unusual thaw in the bog reveals a buried heirloom from a prominent local estate.',
    isbn: '9780593299777',
    formats: [
      { type: 'hardcover', releaseDate: '2026-09-15', price: '$30.00', pageCount: 432 },
      { type: 'ebook', releaseDate: '2026-09-15', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-09-15', price: '$27.00', narrator: 'Roger Clark' },
    ],
    anticipatedCount: 1870,
    primaryReleaseDate: '2026-09-15',
  },
  {
    id: 'book-026',
    title: 'Heartstopper: Forever and Always',
    author: 'Alice Oseman',
    authorBio: 'Award-winning author, illustrator, and creator of the beloved Heartstopper graphic novel series.',
    publisher: 'Scholastic',
    imprint: 'Graphix',
    coverImage: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Young Adult', 'Graphic Novel', 'Romance', 'LGBTQ+'],
    series: {
      name: 'Heartstopper',
      number: 6,
      totalInSeries: 6,
    },
    description: 'The triumphant final installment of Nick and Charlie’s journey as they navigate university choices, packing up childhood bedrooms, and celebrating enduring love.',
    isbn: '9781338801958',
    formats: [
      { type: 'hardcover', releaseDate: '2026-09-22', price: '$24.99', pageCount: 320 },
      { type: 'paperback', releaseDate: '2026-09-22', price: '$15.99', pageCount: 320 },
      { type: 'ebook', releaseDate: '2026-09-22', price: '$11.99' },
    ],
    anticipatedCount: 3890,
    primaryReleaseDate: '2026-09-22',
  },
  {
    id: 'book-027',
    title: 'The Quantum Biographer',
    author: 'Walter Isaacson',
    authorBio: 'Bestselling biographer of Elon Musk, Steve Jobs, Leonardo da Vinci, and Einstein.',
    publisher: 'Simon & Schuster',
    imprint: 'Simon & Schuster',
    coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Non-Fiction', 'Biography', 'Science & Nature'],
    description: 'A monumental chronicle of the pioneers of quantum computing and artificial cognitive architecture, tracing how quantum physics will reshape our civilization.',
    isbn: '9781982181284',
    formats: [
      { type: 'hardcover', releaseDate: '2026-09-29', price: '$36.00', pageCount: 624 },
      { type: 'ebook', releaseDate: '2026-09-29', price: '$16.99' },
      { type: 'audiobook', releaseDate: '2026-09-29', price: '$32.00' },
    ],
    anticipatedCount: 1450,
    primaryReleaseDate: '2026-09-29',
  },

  // --- OCTOBER 2026 RELEASES ---
  {
    id: 'book-028',
    title: 'The Haunting of Hollow Hearth',
    author: 'Stephen King',
    authorBio: 'The legendary Master of Horror with over 60 worldwide bestselling novels.',
    publisher: 'Simon & Schuster',
    imprint: 'Scribner',
    coverImage: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Horror', 'Supernatural', 'Thriller'],
    description: 'A retired radio host buys an old colonial lighthouse in Maine with a mysterious basement chamber that broadcasts ghostly maritime distress signals on silent frequencies.',
    isbn: '9781668045992',
    formats: [
      { type: 'hardcover', releaseDate: '2026-10-06', price: '$32.00', pageCount: 528 },
      { type: 'ebook', releaseDate: '2026-10-06', price: '$15.99' },
      { type: 'audiobook', releaseDate: '2026-10-06', price: '$29.99', narrator: 'Will Patton' },
    ],
    anticipatedCount: 4100,
    featuredQuote: '“Monsters don’t live under your bed; they wait patiently in the static between your favorite radio stations.”',
    pageCount: 528,
    primaryReleaseDate: '2026-10-06',
  },
  {
    id: 'book-029',
    title: 'The Glass Hotelier of Paris',
    author: 'Kristin Hannah',
    authorBio: '#1 New York Times bestselling author of The Women, The Nightingale, and The Great Alone.',
    publisher: 'Macmillan',
    imprint: 'St. Martin’s Press',
    coverImage: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Historical Fiction', 'Drama', 'War & Resistance'],
    description: 'During the liberation of Paris in 1944, a brave concierge secretly shelters Jewish musicians in the subterranean wine vaults of a luxury hotel on Place Vendôme.',
    isbn: '9781250178657',
    formats: [
      { type: 'hardcover', releaseDate: '2026-10-13', price: '$30.00', pageCount: 480 },
      { type: 'ebook', releaseDate: '2026-10-13', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-10-13', price: '$27.50' },
    ],
    anticipatedCount: 3200,
    primaryReleaseDate: '2026-10-13',
  },
  {
    id: 'book-030',
    title: 'The Witch’s Guild of Greenwich',
    author: 'T. Kingfisher',
    authorBio: 'Hugo and Nebula award-winning author of Nettle & Bone and Paladin’s Grace.',
    publisher: 'Tor Publishing Group',
    imprint: 'Tor Books',
    coverImage: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Fantasy', 'Cozy Fantasy', 'Horror'],
    description: 'An pragmatic hedge-witch who specializes in curing sour milk and un-haunting antique clocks is recruited to investigate a dead bishop whose ghost won’t stop offering unsolicited gardening advice.',
    isbn: '9781250830807',
    formats: [
      { type: 'hardcover', releaseDate: '2026-10-20', price: '$26.99', pageCount: 336 },
      { type: 'ebook', releaseDate: '2026-10-20', price: '$13.99' },
      { type: 'audiobook', releaseDate: '2026-10-20', price: '$22.00' },
    ],
    anticipatedCount: 1650,
    primaryReleaseDate: '2026-10-20',
  },

  // --- JULY 2026 RELEASES (RECENT / PAST) ---
  {
    id: 'book-031',
    title: 'The Sunlit Spire',
    author: 'N.K. Jemisin',
    authorBio: 'Record-breaking three-time consecutive Hugo Award winner for The Broken Earth trilogy.',
    publisher: 'Hachette Book Group',
    imprint: 'Orbit',
    coverImage: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Fantasy', 'Sci-Fi', 'Urban Fantasy'],
    description: 'A revolutionary magical engineer discovers that the gleaming solar spires powering the world’s cleanest metropolis are draining life force from an alternate submerged city.',
    isbn: '9780316498776',
    formats: [
      { type: 'hardcover', releaseDate: '2026-07-14', price: '$30.00', pageCount: 464 },
      { type: 'ebook', releaseDate: '2026-07-14', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-07-14', price: '$28.00' },
      { type: 'paperback', releaseDate: '2027-02-09', price: '$19.00' },
    ],
    anticipatedCount: 2900,
    primaryReleaseDate: '2026-07-14',
  },
  {
    id: 'book-032',
    title: 'The Seven Lies of Evelyn Gray',
    author: 'Taylor Jenkins Reid',
    authorBio: 'Bestselling author of Daisy Jones & The Six and The Seven Husbands of Evelyn Hugo.',
    publisher: 'Penguin Random House',
    imprint: 'Ballantine Books',
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Historical Fiction', 'Drama', 'Pop Culture'],
    description: 'In 1970s London, a legendary fashion muse and underground record producer recounts the high-stakes deceit behind the defining rock album of a generation.',
    isbn: '9780593498880',
    formats: [
      { type: 'hardcover', releaseDate: '2026-07-21', price: '$29.00', pageCount: 400 },
      { type: 'ebook', releaseDate: '2026-07-21', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-07-21', price: '$26.00' },
    ],
    anticipatedCount: 3100,
    primaryReleaseDate: '2026-07-21',
  },
  {
    id: 'book-033',
    title: 'Tomorrow, We Sail Again',
    author: 'Gabrielle Zevin',
    authorBio: 'Bestselling author of Tomorrow, and Tomorrow, and Tomorrow.',
    publisher: 'Knopf Doubleday',
    imprint: 'Alfred A. Knopf',
    coverImage: 'https://images.unsplash.com/photo-1507842229451-9f22be21c127?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Literary Fiction', 'Contemporary Fiction', 'Art & Tech'],
    description: 'An intimate chronicle of three indie board game creators across two decades as their handcrafted strategy game evolves from a college kitchen table prototype into a global cultural phenomenon.',
    isbn: '9780593321201',
    formats: [
      { type: 'hardcover', releaseDate: '2026-07-28', price: '$29.00', pageCount: 416 },
      { type: 'ebook', releaseDate: '2026-07-28', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-07-28', price: '$26.50' },
    ],
    anticipatedCount: 2600,
    primaryReleaseDate: '2026-07-28',
  },

  // --- ADDITIONAL RICH TITLES TO REACH FULL 65+ CURATED SET ---
  {
    id: 'book-034',
    title: 'The Bookshop of Hidden Waters',
    author: 'Susanna Clarke',
    authorBio: 'Author of Jonathan Strange & Mr Norrell and Piranesi.',
    publisher: 'Bloomsbury Publishing',
    imprint: 'Bloomsbury Circus',
    coverImage: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Fantasy', 'Literary Fantasy', 'Magical Realism'],
    description: 'A solitary bookbinder in a flooded cathedral city mends volumes that bleed salty tide water whenever their pages are turned by someone harboring a broken promise.',
    isbn: '9781635576023',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-11', price: '$28.00', pageCount: 288 },
      { type: 'ebook', releaseDate: '2026-08-11', price: '$13.99' },
      { type: 'audiobook', releaseDate: '2026-08-11', price: '$22.00', narrator: 'Chiwetel Ejiofor' },
    ],
    anticipatedCount: 2450,
    primaryReleaseDate: '2026-08-11',
  },
  {
    id: 'book-035',
    title: 'The Silent Partner',
    author: 'Lisa Jewell',
    authorBio: '#1 New York Times bestselling author of None of This Is True and Then She Was Gone.',
    publisher: 'Simon & Schuster',
    imprint: 'Atria Books',
    coverImage: 'https://images.unsplash.com/photo-1473186578172-c141e6798cf4?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Mystery & Thriller', 'Domestic Suspense', 'Crime'],
    description: 'When a beloved podcaster’s recording studio is vandalized, an obsessive neighbor volunteers to install security cameras, capturing footage that uncovers an impostor living next door.',
    isbn: '9781982178949',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-14', price: '$28.99', pageCount: 368 },
      { type: 'ebook', releaseDate: '2026-08-14', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-08-14', price: '$25.00' },
    ],
    anticipatedCount: 1680,
    primaryReleaseDate: '2026-08-14',
  },
  {
    id: 'book-036',
    title: 'The Memory Thieves of Kyoto',
    author: 'Kazuo Ishiguro',
    authorBio: 'Nobel Prize in Literature laureate and author of Never Let Me Go and Klara and the Sun.',
    publisher: 'Knopf Doubleday',
    imprint: 'Alfred A. Knopf',
    coverImage: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Literary Fiction', 'Sci-Fi', 'Speculative'],
    description: 'In near-future Japan, an elderly master tea craftsman agrees to rent his memory palace to an artificial intelligence firm seeking the neural imprint of authentic human nostalgia.',
    isbn: '9780593318188',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-26', price: '$30.00', pageCount: 336 },
      { type: 'ebook', releaseDate: '2026-08-26', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-08-26', price: '$26.00' },
    ],
    anticipatedCount: 2980,
    featuredQuote: '“Do not mourn what the machine forgets; mourn rather what it creates in the shape of our sorrow.”',
    pageCount: 336,
    primaryReleaseDate: '2026-08-26',
  },
  {
    id: 'book-037',
    title: 'Just for the Summer Break',
    author: 'Abby Jimenez',
    authorBio: 'New York Times bestselling author of Just for the Summer and Yours Truly.',
    publisher: 'Hachette Book Group',
    imprint: 'Forever',
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Romance', 'Romantic Comedy', 'Contemporary'],
    description: 'An emergency room doctor and a travelling adventure travel vlogger find unexpected comfort and hilarity in a shared Minnesota lakeside cabin during a two-week rainstorm.',
    isbn: '9781538704448',
    formats: [
      { type: 'paperback', releaseDate: '2026-08-18', price: '$18.99', pageCount: 416 },
      { type: 'ebook', releaseDate: '2026-08-18', price: '$12.99' },
      { type: 'audiobook', releaseDate: '2026-08-18', price: '$23.00' },
    ],
    anticipatedCount: 1840,
    primaryReleaseDate: '2026-08-18',
  },
  {
    id: 'book-038',
    title: 'The Pale Shore',
    author: 'Paul Tremblay',
    authorBio: 'Bram Stoker Award-winning author of The Cabin at the End of the World and Horror Movie.',
    publisher: 'HarperCollins',
    imprint: 'William Morrow',
    coverImage: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Horror', 'Psychological Horror', 'Suspense'],
    description: 'A marine biologist observing whale acoustics off Cape Cod begins recording vocalizations that mirror human speech, culminating in an unnerving night where the tide refuses to recede.',
    isbn: '9780063079984',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-21', price: '$28.99', pageCount: 320 },
      { type: 'ebook', releaseDate: '2026-08-21', price: '$13.99' },
      { type: 'audiobook', releaseDate: '2026-08-21', price: '$24.00' },
    ],
    anticipatedCount: 1290,
    primaryReleaseDate: '2026-08-21',
  },
  {
    id: 'book-039',
    title: 'The Way of Kings: Leatherbound Edition',
    author: 'Brandon Sanderson',
    authorBio: '#1 New York Times bestselling author of the Cosmere universe.',
    publisher: 'Dragonsteel Entertainment',
    imprint: 'Dragonsteel Books',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Fantasy', 'Epic Fantasy', 'Cosmere'],
    description: 'Deluxe anniversary bonded-leather two-volume foil edition featuring full-color endpapers, author notes, and interior spot illustrations.',
    isbn: '9781938570308',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-26', price: '$250.00', pageCount: 1120 },
    ],
    anticipatedCount: 3800,
    primaryReleaseDate: '2026-08-26',
  },
  {
    id: 'book-040',
    title: 'The Shadow of the Golden Gate',
    author: 'David Grann',
    authorBio: '#1 New York Times bestselling author of Killers of the Flower Moon and The Wager.',
    publisher: 'Knopf Doubleday',
    imprint: 'Doubleday',
    coverImage: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Non-Fiction', 'History', 'True Crime'],
    description: 'A tour de force narrative of the daring divers and construction crews who risked death in treacherous Pacific currents to build San Francisco’s Golden Gate Bridge amidst the Great Depression.',
    isbn: '9780385534277',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-28', price: '$32.00', pageCount: 416 },
      { type: 'ebook', releaseDate: '2026-08-28', price: '$15.99' },
      { type: 'audiobook', releaseDate: '2026-08-28', price: '$28.00' },
    ],
    anticipatedCount: 1950,
    primaryReleaseDate: '2026-08-28',
  },
  {
    id: 'book-041',
    title: 'The Velvet Keyhole',
    author: 'Casey McQuiston',
    authorBio: 'Bestselling author of Red, White & Royal Blue and One Last Stop.',
    publisher: 'Macmillan',
    imprint: 'St. Martin’s Griffin',
    coverImage: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Romance', 'Romantic Comedy', 'LGBTQ+'],
    description: 'Two rival vintage clothing curators in Brooklyn find an encrypted diary sewn into the silk lining of a 1950s Dior evening coat, setting off a transatlantic scavenger hunt.',
    isbn: '9781250860552',
    formats: [
      { type: 'paperback', releaseDate: '2026-08-26', price: '$19.00', pageCount: 384 },
      { type: 'ebook', releaseDate: '2026-08-26', price: '$13.99' },
      { type: 'audiobook', releaseDate: '2026-08-26', price: '$24.00' },
    ],
    anticipatedCount: 1720,
    primaryReleaseDate: '2026-08-26',
  },
  {
    id: 'book-042',
    title: 'A Feather on the Gale',
    author: 'Barbara Kingsolver',
    authorBio: 'Pulitzer Prize-winning author of Demon Copperhead and The Poisonwood Bible.',
    publisher: 'HarperCollins',
    imprint: 'Harper',
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Literary Fiction', 'Historical Fiction', 'Appalachia'],
    description: 'Set during the 1930s labor strikes in the blue mist hollows of southern Virginia, a young woman learns herbal medicine from her grandmother while navigating industrial strife.',
    isbn: '9780063252003',
    formats: [
      { type: 'hardcover', releaseDate: '2026-09-01', price: '$32.00', pageCount: 544 },
      { type: 'ebook', releaseDate: '2026-09-01', price: '$15.99' },
      { type: 'audiobook', releaseDate: '2026-09-01', price: '$29.00' },
    ],
    anticipatedCount: 2280,
    primaryReleaseDate: '2026-09-01',
  },
  {
    id: 'book-043',
    title: 'The Witch of the Iron Forest',
    author: 'Grady Hendrix',
    authorBio: 'Bestselling author of How to Sell a Haunted House and The Southern Book Club’s Guide to Slaying Vampires.',
    publisher: 'Penguin Random House',
    imprint: 'Berkley',
    coverImage: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Horror', 'Comedy Horror', 'Supernatural'],
    description: 'When a suburban hardware store manager inherits an abandoned scrap yard in Pennsylvania, he discovers the rusting industrial machinery is being operated by 17th-century coven ghosts.',
    isbn: '9780593201305',
    formats: [
      { type: 'hardcover', releaseDate: '2026-09-08', price: '$29.00', pageCount: 384 },
      { type: 'ebook', releaseDate: '2026-09-08', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-09-08', price: '$25.00' },
    ],
    anticipatedCount: 1640,
    primaryReleaseDate: '2026-09-08',
  },
  {
    id: 'book-044',
    title: 'The Cartographer’s Secret Ink',
    author: 'Anthony Horowitz',
    authorBio: 'Bestselling creator of the Magpie Murders series and Alex Rider novels.',
    publisher: 'HarperCollins',
    imprint: 'Harper',
    coverImage: 'https://images.unsplash.com/photo-1507842229451-9f22be21c127?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Mystery & Thriller', 'Whodunit', 'Literary Mystery'],
    series: {
      name: 'Hawthorne and Horowitz',
      number: 6,
    },
    description: 'Anthony Horowitz reluctantly teams up once more with the enigmatic ex-detective Daniel Hawthorne to solve the murder of a rare book dealer poisoned at the British Library.',
    isbn: '9780063305587',
    formats: [
      { type: 'hardcover', releaseDate: '2026-09-15', price: '$28.99', pageCount: 368 },
      { type: 'ebook', releaseDate: '2026-09-15', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-09-15', price: '$24.50' },
    ],
    anticipatedCount: 1470,
    primaryReleaseDate: '2026-09-15',
  },
  {
    id: 'book-045',
    title: 'Echoes Across the Chasm',
    author: 'Percival Everett',
    authorBio: 'Pulitzer Prize winner for James and author of The Trees and Erasure.',
    publisher: 'Knopf Doubleday',
    imprint: 'Doubleday',
    coverImage: 'https://images.unsplash.com/photo-1473186578172-c141e6798cf4?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Literary Fiction', 'Satire', 'Western'],
    description: 'A sharp, subversive retelling of an 1880s New Mexico land dispute, weaving philosophical humor, frontier linguistics, and blistering critiques of myth-making.',
    isbn: '9780385550406',
    formats: [
      { type: 'hardcover', releaseDate: '2026-09-22', price: '$28.00', pageCount: 304 },
      { type: 'ebook', releaseDate: '2026-09-22', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-09-22', price: '$24.00' },
    ],
    anticipatedCount: 1980,
    primaryReleaseDate: '2026-09-22',
  },
  {
    id: 'book-046',
    title: 'The Starlight Foundry',
    author: 'Samantha Shannon',
    authorBio: 'New York Times bestselling author of The Bone Season and Roots of Chaos.',
    publisher: 'Bloomsbury Publishing',
    imprint: 'Bloomsbury Circus',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Fantasy', 'Dystopian', 'Sci-Fi'],
    series: {
      name: 'The Bone Season',
      number: 6,
      totalInSeries: 7,
    },
    description: 'Paige Mahoney rallies the clairvoyant underground across Scion Europe as the syndicate prepares for an all-out assault against the ethereal Rephaite overlords.',
    isbn: '9781635579994',
    formats: [
      { type: 'hardcover', releaseDate: '2026-09-29', price: '$30.00', pageCount: 512 },
      { type: 'ebook', releaseDate: '2026-09-29', price: '$15.99' },
      { type: 'audiobook', releaseDate: '2026-09-29', price: '$27.50' },
    ],
    anticipatedCount: 2150,
    primaryReleaseDate: '2026-09-29',
  },
  {
    id: 'book-047',
    title: 'The Silent Ledger',
    author: 'Ken Follett',
    authorBio: 'Worldwide bestselling author of The Pillars of the Earth and the Kingsbridge series.',
    publisher: 'Penguin Random House',
    imprint: 'Viking',
    coverImage: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Historical Fiction', 'Epic Fiction', 'Drama'],
    series: {
      name: 'Kingsbridge',
      number: 6,
    },
    description: 'In 1870s Victorian England, the introduction of steam railways and telegraphy splits the stone-mason dynasties of Kingsbridge into fiercely contested factions.',
    isbn: '9780525954996',
    formats: [
      { type: 'hardcover', releaseDate: '2026-10-06', price: '$36.00', pageCount: 880 },
      { type: 'ebook', releaseDate: '2026-10-06', price: '$16.99' },
      { type: 'audiobook', releaseDate: '2026-10-06', price: '$34.00' },
    ],
    anticipatedCount: 2600,
    primaryReleaseDate: '2026-10-06',
  },
  {
    id: 'book-048',
    title: 'The Girl Who Spoke to Crows',
    author: 'Tomi Adeyemi',
    authorBio: '#1 New York Times bestselling author of Children of Blood and Bone.',
    publisher: 'Macmillan',
    imprint: 'Henry Holt and Co.',
    coverImage: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Young Adult', 'Fantasy', 'Mythology'],
    description: 'A new West African-inspired dark fantasy realm where an outcast avian summoner must reclaim her ancestral throne from a usurper king cloaked in shadow magic.',
    isbn: '9781250170996',
    formats: [
      { type: 'hardcover', releaseDate: '2026-10-13', price: '$24.99', pageCount: 432 },
      { type: 'ebook', releaseDate: '2026-10-13', price: '$12.99' },
      { type: 'audiobook', releaseDate: '2026-10-13', price: '$22.50' },
    ],
    anticipatedCount: 2300,
    primaryReleaseDate: '2026-10-13',
  },
  {
    id: 'book-049',
    title: 'Under the Spindle Tree',
    author: 'Chloe Liese',
    authorBio: 'Author of the Bergman Brothers series and Better Hate Than Never.',
    publisher: 'Penguin Random House',
    imprint: 'Berkley',
    coverImage: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Romance', 'Romantic Comedy', 'Neurodiverse Romance'],
    description: 'A sweet, enemies-to-lovers retelling of Sleeping Beauty featuring a neurodivergent rare book conservator and an exasperatingly charming audio archivist.',
    isbn: '9780593548981',
    formats: [
      { type: 'paperback', releaseDate: '2026-08-04', price: '$18.00', pageCount: 368 },
      { type: 'ebook', releaseDate: '2026-08-04', price: '$12.99' },
      { type: 'audiobook', releaseDate: '2026-08-04', price: '$22.00' },
    ],
    anticipatedCount: 1100,
    primaryReleaseDate: '2026-08-04',
  },
  {
    id: 'book-050',
    title: 'The Shadow Cabinet of Whitechapel',
    author: 'Catriona Ward',
    authorBio: 'Multi-award-winning author of The Last House on Needless Street and Sundial.',
    publisher: 'Tor Publishing Group',
    imprint: 'Tor Nightfire',
    coverImage: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Horror', 'Gothic Horror', 'Historical Thriller'],
    description: 'In 1895 London, an anatomy taxidermist discovers that the wax mannequins in Madame Tussaud’s basement are whispering real courtroom testimony before crimes occur.',
    isbn: '9781250860019',
    formats: [
      { type: 'hardcover', releaseDate: '2026-10-27', price: '$28.99', pageCount: 352 },
      { type: 'ebook', releaseDate: '2026-10-27', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-10-27', price: '$24.00' },
    ],
    anticipatedCount: 1480,
    primaryReleaseDate: '2026-10-27',
  },
  {
    id: 'book-051',
    title: 'The Ocean in Winter',
    author: 'Ocean Vuong',
    authorBio: 'MacArthur Fellow and author of On Earth We’re Briefly Gorgeous and Time Is a Mother.',
    publisher: 'Penguin Random House',
    imprint: 'Penguin Press',
    coverImage: 'https://images.unsplash.com/photo-1507842229451-9f22be21c127?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Literary Fiction', 'Poetry & Prose', 'LGBTQ+'],
    description: 'A luminous, heartbreaking novel exploring immigration, queer love, Buddhist funeral rites, and generational memory along the freezing coast of New England.',
    isbn: '9780593490013',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-26', price: '$28.00', pageCount: 272 },
      { type: 'ebook', releaseDate: '2026-08-26', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-08-26', price: '$24.00', narrator: 'Ocean Vuong' },
    ],
    anticipatedCount: 2840,
    featuredQuote: '“To love another is to offer them a glass of water while the house is on fire.”',
    pageCount: 272,
    primaryReleaseDate: '2026-08-26',
  },
  {
    id: 'book-052',
    title: 'Doppelgänger: The New Frontiers',
    author: 'Naomi Klein',
    authorBio: 'Bestselling author of Shock Doctrine, This Changes Everything, and Doppelganger.',
    publisher: 'Farrar, Straus and Giroux',
    imprint: 'FSG',
    coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Non-Fiction', 'Politics & Society', 'Essays'],
    description: 'A profound cultural diagnosis of algorithmic mirror-worlds, political disassociation, and how societies can rebuild solidarity in an age of synthetic identities.',
    isbn: '9780374610340',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-11', price: '$30.00', pageCount: 416 },
      { type: 'ebook', releaseDate: '2026-08-11', price: '$15.99' },
      { type: 'audiobook', releaseDate: '2026-08-11', price: '$26.50' },
    ],
    anticipatedCount: 1120,
    primaryReleaseDate: '2026-08-11',
  },
  {
    id: 'book-053',
    title: 'A Court of Frost and Starlight (Special Anniversary Edition)',
    author: 'Sarah J. Maas',
    authorBio: '#1 New York Times bestselling author of the ACOTAR and Crescent City series.',
    publisher: 'Bloomsbury Publishing',
    imprint: 'Bloomsbury YA',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Fantasy', 'Romance', 'Young Adult'],
    description: 'Special foiled edges and illustrated dust jacket celebrating the Winter Solstice in the Night Court with exclusive author commentary.',
    isbn: '9781681196312',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-26', price: '$32.00', pageCount: 272 },
    ],
    anticipatedCount: 3900,
    primaryReleaseDate: '2026-08-26',
  },
  {
    id: 'book-054',
    title: 'The Map of Unbroken Promises',
    author: 'Min Jin Lee',
    authorBio: 'National Book Award Finalist and New York Times bestselling author of Pachinko.',
    publisher: 'Hachette Book Group',
    imprint: 'Grand Central Publishing',
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Historical Fiction', 'Literary Fiction', 'Family Saga'],
    description: 'An epic third novel in the Korean diaspora trilogy, following students, activists, and engineers in Seoul and Boston from 1988 to the 2002 World Cup.',
    isbn: '9781538722343',
    formats: [
      { type: 'hardcover', releaseDate: '2026-11-03', price: '$32.00', pageCount: 528 },
      { type: 'ebook', releaseDate: '2026-11-03', price: '$15.99' },
      { type: 'audiobook', releaseDate: '2026-11-03', price: '$29.00' },
    ],
    anticipatedCount: 2950,
    primaryReleaseDate: '2026-11-03',
  },
  {
    id: 'book-055',
    title: 'The Quantum Weaver',
    author: 'Cathy O’Neil',
    authorBio: 'Mathematician, data scientist, and bestselling author of Weapons of Math Destruction.',
    publisher: 'Penguin Random House',
    imprint: 'Crown',
    coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Non-Fiction', 'Technology', 'Ethics & AI'],
    description: 'A critical framework for democratizing machine learning architectures and protecting public civil liberties in an era of automated governance.',
    isbn: '9780593444009',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-18', price: '$30.00', pageCount: 352 },
      { type: 'ebook', releaseDate: '2026-08-18', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-08-18', price: '$24.00' },
    ],
    anticipatedCount: 890,
    primaryReleaseDate: '2026-08-18',
  },
  {
    id: 'book-056',
    title: 'The Silent Hour at Sea',
    author: 'Emma Cline',
    authorBio: 'Bestselling author of The Girls and The Guest.',
    publisher: 'Random House',
    imprint: 'Random House',
    coverImage: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Literary Fiction', 'Psychological Fiction', 'Contemporary'],
    description: 'A suspenseful, sun-drenched psychological novel about a nanny marooned on a private Aegean yacht when the billionaire family unexpectedly abandons ship.',
    isbn: '9780812998627',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-25', price: '$28.00', pageCount: 288 },
      { type: 'ebook', releaseDate: '2026-08-25', price: '$14.99' },
      { type: 'audiobook', releaseDate: '2026-08-25', price: '$23.00' },
    ],
    anticipatedCount: 1620,
    primaryReleaseDate: '2026-08-25',
  },
  {
    id: 'book-057',
    title: 'The Iron Heart of the Mountain',
    author: 'Gillian Flynn',
    authorBio: '#1 New York Times bestselling author of Gone Girl and Sharp Objects.',
    publisher: 'Penguin Random House',
    imprint: 'Crown',
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Mystery & Thriller', 'Dark Thriller', 'Suspense'],
    description: 'Flynn’s long-awaited original thriller set in a defunct copper mining town in Montana, where the discovery of three embalmed bodies inside a mine elevator exposes a vicious family dynasty.',
    isbn: '9780307341570',
    formats: [
      { type: 'hardcover', releaseDate: '2026-10-20', price: '$30.00', pageCount: 448 },
      { type: 'ebook', releaseDate: '2026-10-20', price: '$15.99' },
      { type: 'audiobook', releaseDate: '2026-10-20', price: '$28.00' },
    ],
    anticipatedCount: 4200,
    primaryReleaseDate: '2026-10-20',
  },
  {
    id: 'book-058',
    title: 'Atomic Habits: The Workbook & Companion',
    author: 'James Clear',
    authorBio: '#1 New York Times bestselling author of Atomic Habits.',
    publisher: 'Penguin Random House',
    imprint: 'Avery',
    coverImage: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Non-Fiction', 'Self-Help', 'Productivity'],
    description: 'A comprehensive, hands-on structured guide featuring daily habit trackers, implementation intention templates, and environmental design checklists.',
    isbn: '9780735211308',
    formats: [
      { type: 'paperback', releaseDate: '2026-08-26', price: '$22.00', pageCount: 256 },
      { type: 'ebook', releaseDate: '2026-08-26', price: '$12.99' },
    ],
    anticipatedCount: 1540,
    primaryReleaseDate: '2026-08-26',
  },
  {
    id: 'book-059',
    title: 'The Seven Sins of Sorcery',
    author: 'Hannah Grace',
    authorBio: '#1 New York Times bestselling author of Icebreaker and Wildfire.',
    publisher: 'Simon & Schuster',
    imprint: 'Atria Books',
    coverImage: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Romance', 'Sports Romance', 'Contemporary Fiction'],
    description: 'A collegiate ice hockey captain and a competitive synchronized skater fake a relationship to navigate media attention before their respective Olympic trials.',
    isbn: '9781668026304',
    formats: [
      { type: 'paperback', releaseDate: '2026-08-26', price: '$19.99', pageCount: 432 },
      { type: 'ebook', releaseDate: '2026-08-26', price: '$13.99' },
      { type: 'audiobook', releaseDate: '2026-08-26', price: '$24.00' },
    ],
    anticipatedCount: 2200,
    primaryReleaseDate: '2026-08-26',
  },
  {
    id: 'book-060',
    title: 'The Shadow of the Sun',
    author: 'Rainbow Rowell',
    authorBio: '#1 New York Times bestselling author of Eleanor & Park and the Simon Snow trilogy.',
    publisher: 'Macmillan',
    imprint: 'Wednesday Books',
    coverImage: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=600&q=80',
    genreTags: ['Young Adult', 'Contemporary', 'Coming of Age'],
    description: 'A warm and hilarious coming-of-age story about two theater nerds who spend their senior year building an elaborate miniature replica of an abandoned drive-in movie theater.',
    isbn: '9781250761231',
    formats: [
      { type: 'hardcover', releaseDate: '2026-08-26', price: '$22.99', pageCount: 352 },
      { type: 'ebook', releaseDate: '2026-08-26', price: '$11.99' },
      { type: 'audiobook', releaseDate: '2026-08-26', price: '$21.00' },
    ],
    anticipatedCount: 1490,
    primaryReleaseDate: '2026-08-26',
  }
];

// --- THIS DAY IN PUBLISHING HISTORY (Historical Releases) ---
export const PUBLISHING_HISTORY_ENTRIES: PublishingHistoryEntry[] = [
  {
    id: 'hist-0826',
    title: 'Lolita (US First Edition)',
    author: 'Vladimir Nabokov',
    originalReleaseDate: '1958-08-26',
    originalYear: 1958,
    publisher: 'G.P. Putnam’s Sons',
    coverImage: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=600&q=80',
    genre: 'Classic / Literary Fiction',
    historicalFact: 'On August 26, 1958, G.P. Putnam’s Sons published the first American edition of Lolita after years of censorship battles. It became the first novel since Gone with the Wind to sell 100,000 copies in its first three weeks.',
    legacyImpact: 'Nabokov’s masterpiece redefined modern prose styling, unreliable narration, and the boundaries of literary freedom in the 20th century.',
    isbn: '9780679723165',
  },
  {
    id: 'hist-0804',
    title: 'Dune (First Book Club Edition)',
    author: 'Frank Herbert',
    originalReleaseDate: '1965-08-04',
    originalYear: 1965,
    publisher: 'Chilton Book Company',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    genre: 'Science Fiction',
    historicalFact: 'Frank Herbert’s Dune was rejected by over twenty publishers before Chilton, an auto-repair manual publisher, took a gamble and released it in hardcover in August 1965.',
    legacyImpact: 'Winner of both the Hugo and Nebula Awards, Dune became the best-selling science fiction epic of all time and laid the foundation for modern world-building.',
    isbn: '9780441172719',
  },
  {
    id: 'hist-0818',
    title: 'Lolita (Olympia Press Paris Edition)',
    author: 'Vladimir Nabokov',
    originalReleaseDate: '1955-08-18',
    originalYear: 1955,
    publisher: 'Olympia Press',
    coverImage: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80',
    genre: 'Literary Fiction',
    historicalFact: 'First published in Paris as two green paperbound volumes by Maurice Girodias at Olympia Press in August 1955 before international acclaim brought it to world stages.',
    legacyImpact: 'Demonstrated the power of international literary distribution and translation.',
    isbn: '9780141182537',
  },
  {
    id: 'hist-0830',
    title: 'Frankenstein (1818 First US / London Serialized)',
    author: 'Mary Shelley',
    originalReleaseDate: '1818-08-30',
    originalYear: 1818,
    publisher: 'Lackington, Hughes, Harding, Mavor, & Jones',
    coverImage: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=600&q=80',
    genre: 'Gothic / Science Fiction',
    historicalFact: 'Written by Mary Shelley at age nineteen, the landmark Gothic novel established the foundational template for the entire modern science fiction genre.',
    legacyImpact: 'Created the modern myth of scientific hubris and artificial life.',
    isbn: '9780141439471',
  },
  {
    id: 'hist-0811',
    title: 'The Left Hand of Darkness',
    author: 'Ursula K. Le Guin',
    originalReleaseDate: '1969-08-11',
    originalYear: 1969,
    publisher: 'Ace Science Fiction',
    coverImage: 'https://images.unsplash.com/photo-1532012164546-f432f2e37264?auto=format&fit=crop&w=600&q=80',
    genre: 'Science Fiction',
    historicalFact: 'Ace Books published Le Guin’s Hainish Cycle masterpiece in August 1969, sweeping both the Hugo and Nebula Awards.',
    legacyImpact: 'Revolutionized gender, sexuality, and cultural anthropology in speculative literature.',
    isbn: '9780441478125',
  }
];
